import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class VehiclesService {

  constructor() { }
  carData = [
    {
      id: 1,
      name: 'Mitsubishi',
      color: 'Yellow',
      model: 2002,
      price: '$2814.46',
      category: 'SUV',
      fuel_type: 'Gasoline',
      category_id : 1,
      description: 'Reliable SUV, great mileage, perfect for outdoor adventures.',
    },
    {
      id: 2,
      name: 'Ford',
      color: 'Maroon',
      model: 2008,
      price: '$1731.98',
      category: 'Sedan',
      category_id : 2,
      fuel_type: 'Diesel',
      description: 'Elegant sedan, advanced features, excellent fuel efficiency.',
    },
    {
      id: 3,
      name: 'Saturn',
      color: 'Red',
      model: 2003,
      price: '$2238.35',
      category: 'Sedan',
      category_id : 2,
      fuel_type: 'Gasoline',
      description: 'Classic sedan design, reliable performance, suitable for daily commute.',
    },
    {
      id: 4,
      name: 'Jeep',
      color: 'Violet',
      model: 2012,
      price: '$2732.99',
      category: 'SUV',
      fuel_type: 'Gasoline',
      category_id : 1,
      description: 'Powerful SUV, bold design, capable off-road vehicle.',
    },
    {
      id: 5,
      name: 'Lexus RX',
      color: 'Purple',
      model: 2002,
      price: '$3849.47',
      category: 'Sedan',
      category_id : 2,
      fuel_type: 'Gasoline',
      description: 'Sporty sedan, unique design, impressive performance and handling.',
    },
    {
      id: 6,
      name: 'GMC Sierra',
      color: 'Indigo',
      model: 2009,
      price: '$1252.30',
      category: 'SUV',
      category_id : 1,
      fuel_type: 'Gasoline',
      description: 'Spacious SUV, comfortable interior, ideal for family trips.',
    },
    {
      id: 7,
      name: 'Dodge',
      color: 'Yellow',
      model: 1994,
      price: '$1762.42',
      category: 'Van',
      category_id : 3,
      fuel_type: 'Diesel',
      description: 'Classic van, reliable and versatile transportation solution.',
    },
    {
      id: 8,
      name: 'Isuzu',
      color: 'Teal',
      model: 2004,
      price: '$1081.40',
      category: 'SUV',
      category_id : 1,
      fuel_type: 'Diesel',
      description: 'Sturdy SUV, rugged design, suitable for off-road exploration.',
    },
    {
      id: 9,
      name: 'BMW',
      color: 'Purple',
      model: 2008,
      price: '$1258.99',
      category: 'Sedan',
      category_id : 2,
      fuel_type: 'Gasoline',
      description: 'Luxurious sedan, refined features, delivers a premium driving experience.',
    },
    {
      id: 10,
      name: 'Volkswagen ',
      color: 'Purple',
      model: 1994,
      price: '$3822.92',
      category: 'Coupe',
      category_id : 4,
      fuel_type: 'Gasoline',
      description: 'Classic coupe, sporty appearance, offers exhilarating performance.',
    },
    {
      id: 11,
      name: 'Mazda',
      color: 'Red',
      model: 2010,
      price: '$3963.20',
      category: 'Minivan',
      category_id : 6,
      fuel_type: 'Gasoline',
      description: 'Spacious minivan, modern features, perfect for family journeys.',
    },
    {
      id: 12,
      name: 'Audi',
      color: 'Pink',
      model: 2012,
      price: '$1144.27',
      category: 'SUV',
      category_id : 1,
      fuel_type: 'Diesel',
      description: 'Premium SUV, luxurious interior, advanced technology.',
    },
    {
      id: 13,
      name: 'Mercedes-Benz',
      color: 'Aquamarine',
      model: 1989,
      price: '$1386.49',
      category: 'Convertible',
      category_id : 5,
      fuel_type: 'Gasoline',
      description: 'Classic convertible, elegant design, a timeless icon.',
    },
    {
      id: 14,
      name: 'Volvo',
      color: 'Red',
      model: 2012,
      price: '$1366.96',
      category: 'Convertible',
      category_id : 5,
      fuel_type: 'Gasoline',
      description: 'Modern convertible, Scandinavian design, advanced safety features.',
    },
    {
      id: 15,
      name: 'GMC',
      color: 'Green',
      model: 2006,
      price: '$1221.46',
      category: 'SUV',
      category_id : 1,
      fuel_type: 'Gasoline',
      description: 'Stylish SUV, comfortable interior, versatile for city and outdoor drives.',
    },
    {
      id: 16,
      name: 'Kia Soul',
      color: 'Teal',
      model: 1996,
      price: '$1877.63',
      category: 'Van',
      category_id : 3,
      fuel_type: 'Diesel',
      description: 'Durable van, reliable performance, suitable for various purposes.',
    },
    {
      id: 17,
      name: 'Cadillac',
      color: 'Pink',
      model: 2003,
      price: '$2646.55',
      category: 'Sedan',
      category_id : 2,
      fuel_type: 'Gasoline',
      description: 'Luxury sedan, iconic brand, combines style and comfort.',
    },
    ];
    category = [
      {
         id : 1,
         name : 'SUV'
      },
      {
        id : 2,
        name : 'Sedan'
      },
      {
        id : 3,
        name : 'Van'
      },
      {
        id : 4,
        name : 'Coupe'
      },
      {
        id : 5,
        name : 'Convertible'
      },
      {
        id : 6,
        name : 'Minivan'
      }
    ]
}
